### PR TITLE
Pass the source map to source-map-support

### LINKED ISSUE #33: Need to set the retrieveSourceMap option of source-map-support
See discussion in #32 

Root cause is that we're not properly setting either the `retreiveSourceMap` option of `source-map-support`. This causes it to just get the default html of the server and try to treat that as a sourcemap. #oops.

### PR DESCRIPTION
**Pull request by joeybaker**
so… that it actually, you know… works.

Fixes #33

### CODE REVIEW

**Comment by joeybaker** [comment]
Ran the tests locally, and all is well.

**Comment by joeybaker** [comment]
@timoxley here's the fix you requested yesterday :)

**Comment by joeybaker** [comment]
Updated so it's mergable again.

**Comment by joeybaker** [comment]
Thanks @timoxley! Any chance you could publish a new version to NPM?

**Comment by timoxley** [comment]
https://github.com/hughsk/smokestack/compare/v3.2.0...v3.2.1

**Comment by joeybaker** [comment]
Thank you! And nice work on the lack-of-sourcemap functionality!

**Pull request merged**
